### ISSUE TITLE
Create a JSON mock server

### ISSUE THREAD

**Issue by peto85** [2M3com/MyWedding-Front#5]
`To provide a server that returns a JSON representation of a random user:

````{
  user: {
    id: 23,
    name: "John Doe",
    email: "john.doe@nomail.com"
   }
}

**Comment by peto85** [comment]
Podemos empezar con este link:
http://www.mocky.io/v2/5896104a290000bc233f438f

Que produce este JSON:

```
{
    "users": [
        {
            "id": 1,
            "name": "Jonay",
            "email": "cantbefound@nomail.com"
        },
        {
            "id": 2,
            "name": "Gallo",
            "email": "stuckinairport@nomail.com"
        },
        {
            "id": 3,
            "name": "Rodri",
            "email": "zasexcusa@nomail.com"
        },
        {
            "id": 4,
            "name": "Cristo",
            "email": "traelosvasos@nomail.com"
        }
    ]
}
`````

Tengo que investigar bien como va Apiari, pero para empezar esto es más que suficiente.

**Comment by alu0100207385** [comment]
Great, thanks Héctor!

**Comment by davidramosleh** [comment]
Encontré un ejemplo de llamada con ionic2 que usaban este servicio que devuelve un listado de usuarios random. Está muy bien, lo he metido para probar. https://randomuser.me/api/?results=10
